
fields = {
    "水": "shuǐ",
    "人": "rén",
    "手": "shǒu",
    "木": "mù",
    "心": "xīn",
    "口": "kǒu",
    "言": "yán",
    "糸": "mì",
    "辵": "chuò",
    "土": "tǔ",
    "艸": "cǎo",
    "肉": "ròu",
    "阜": "fù",
    "日": "rì",
    "女": "nǚ",
    "宀": "mián",
    "貝": "bèi",
    "金": "jīn",
    "刀": "dāo",
    "火": "huǒ",
    "竹": "zhú",
    "力": "lì",
    "禾": "hé",
    "頁": "yè",
    "衣": "yī",
    "彳": "chì",
    "田": "tián",
    "目": "mù",
    "大": "dà",
    "巾": "jīn",
    "广": "guǎng",
    "犬": "quǎn",
    "一": "yī",
    "山": "shān",
    "攵": "攵",
    "石": "shí",
    "尸": "shī",
    "玉": "yù",
    "疒": "nè",
    "示": "shì",
    "車": "chē",
    "酉": "yǒu",
    "雨": "yǔ",
    "囗": "wéi",
    "寸": "cùn",
    "食": "shí",
    "十": "shí",
    "弓": "gōng",
    "月": "yuè",
    "門": "mén",
    "又": "yòu",
    "子": "zi",
    "欠": "qiàn",
    "牛": "niú",
    "隹": "zhuī",
    "歹": "dǎi",
    "儿": "r",
    "羽": "yǔ",
    "足": "zú",
    "艮": "gèn",
    "穴": "xué",
    "走": "zǒu",
    "毛": "máo",
    "耳": "ěr",
    "見": "jiàn",
    "二": "èr",
    "長": "cháng",
    "羊": "yáng",
    "米": "mǐ",
    "斤": "jīn",
    "小": "xiǎo",
    "止": "zhǐ",
    "豆": "dòu",
    "邑": "yì",
    "卩": "jié",
    "厶": "sī",
    "辛": "xīn",
    "夂": "zhǐ",
    "夕": "xī",
    "厂": "chǎng",
    "戈": "gē",
    "里": "lǐ",
    "白": "bái",
    "八": "bā",
    "戸": "hù",
    "勹": "bāo",
    "立": "lì",
    "巛": "chuān",
    "冫": "bīng",
    "氏": "shì",
    "父": "fù",
    "用": "yòng",
    "网": "wǎng",
    "爪": "zhuǎ",
    "殳": "shū",
    "音": "yīn",
    "乙": "yǐ",
    "斗": "dòu",
    "至": "zhì",
    "冖": "mì",
    "匸": "xì",
    "工": "gōng",
    "首": "shǒu",
    "气": "qì",
    "青": "qīng",
    "毋": "wú",
    "弋": "yì",
    "疋": "yǎ",
    "黄": "huáng",
    "自": "zì",
    "支": "zhī",
    "方": "fāng",
    "谷": "gǔ",
    "行": "xíng",
    "廾": "gǒng",
    "赤": "chì",
    "丶": "zhǔ",
    "干": "gān",
    "廴": "yǐn",
    "生": "shēng",
    "老": "lǎo",
    "己": "jǐ",
    "丨": "shù",
    "矢": "shǐ",
    "彡": "shān",
    "比": "bǐ",
    "色": "sè",
    "入": "rù",
    "文": "wén",
    "彐": "jì",
    "襾": "yà",
    "非": "fēi",
    "士": "shì",
    "几": "jǐ",
    "癶": "bō",
    "亠": "tóu",
    "丿": "piě",
    "卜": "bo",
    "虫": "chóng",
    "冂": "jiōng",
    "亅": "jué",
    "匕": "bǐ",
    "風": "fēng",
    "聿": "yù",
    "高": "gāo",
    "甘": "gān",
    "舌": "shé",
    "矛": "máo",
    "舟": "zhōu",
    "鳥": "niǎo",
    "魚": "yú",
    "馬": "mǎ",
    "身": "shēn",
    "皮": "pí",
    "面": "miàn",
    "黑": "hēi",
    "血": "xuè",
    "幺": "yāo",
    "香": "xiāng",
    "鬼": "guǐ",
    "匚": "fāng",
    "飛": "fēi",
    "片": "piàn",
    "豕": "shǐ",
    "臣": "chén",
    "韋": "wéi",
    "鼻": "bí",
    "爿": "pán",
    "齒": "chǐ",
    "角": "jiǎo",
    "齊": "qí",
    "麥": "mài",
    "皿": "mǐn",
    "瓜": "guā",
    "革": "gé",
    "鹿": "lù",
    "舛": "chuǎn",
    "骨": "gǔ",
    "鼠": "shǔ",
    "辰": "chén",
    "隶": "lì",
    "牙": "yá",
    "凵": "kǎn",
    "屮": "chè",
    "缶": "fǒu",
    "玄": "xuán",
    "龍": "lóng",
    "龜": "guī",
    "无": "wú",
    "鬥": "dòu",
    "臼": "jiù",
    "虍": "hū",
    "鬲": "lì",
    "尢": "wāng",
    "瓦": "wǎ",
    "耒": "lěi",
    "豸": "zhì",
    "黍": "shǔ",
    "鼓": "gǔ",
    "鹵": "lǔ",
    "髟": "biāo",
    "黽": "mǐn",
    "曰": "yuē",
    "麻": "má",
    "而": "ér",
    "韭": "jiǔ",
    "龠": "yuè",
    "爻": "yáo",
    "釆": "biàn",
    "鼎": "dǐng",
    "禸": "róu",
    "鬯": "chàng",
    "黹": "zhǐ",
    "夊": "suī",
}


mainField = "Radical"
targetField = "Pinyin"

def getField(field, note):
    fieldText = note[field]
    from anki.utils import stripHTML
    return stripHTML(fieldText) if fieldText else None

for nid, in mw.col.db.execute(f"select id from notes"):
    note = mw.col.getNote(nid)

    if targetField in note and mainField in note:
        mainFieldText = getField(mainField, note)
        if mainFieldText in fields:
            targetFieldText = getField(targetField, note)
            if targetFieldText is not None:
                if len(targetFieldText):
                    print(f"Warning: Replacing nid {nid}, mainField {mainField} === {targetFieldText}")

            print(f"Setting field '{mainField} -> {targetField}', nid {nid}, {targetFieldText} === {fields[mainFieldText]}")
            note[targetField] = fields[mainFieldText]
            note.flush()
